export const FETCH_COORD = 'FETCH_COORD';
export const DESERIALIZE_COORD = 'DESERIALIZE_COORD';

export const CHANGE_COORDINATE = 'CHANGE_COORDINATE';
export const CHANGE_PLAYER_STATE = 'CHANGE_PLAYER_STATE';
export const CHANGE_PLAYER_TIME = 'CHANGE_PLAYER_TIME';
